2023-07-27 18:09:50,074 - ERROR - Failed to unzip ../../data/raw/archive.zip: [Errno 2] No such file or directory: '../../data/raw/archive.zip'
Traceback (most recent call last):
  File "/home/pedro/Projects/fraud-detection/bank_fraud_detection_project/src/data_preprocessing/unzip_file.py", line 22, in unzip_file
    with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
  File "/usr/lib/python3.10/zipfile.py", line 1249, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '../../data/raw/archive.zip'
